<a href="https://colab.research.google.com/github/ElFeo/machine-learning/blob/master/Ml4t_0103.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [16]:
def test_run():
  print (np.array([2,3,4]))
  print (np.empty((5,4)))
  print (np.zeros((3,4)))
  print (np.ones((3,4), dtype=np.int))
  print (np.random.normal(50,5,(3,4)))

  np.random.seed(666)
  a0 = np.random.randint(0,10, size=(5,4))
  print("Array a0:\n",a0)
  print("Array sum a0:\n",a0.sum())
   
  
if __name__ == "__main__":
  test_run()

[2 3 4]
[[9.9e-324 3.0e-323 4.4e-323 2.0e-323]
 [1.5e-323 4.9e-324 0.0e+000 4.0e-323]
 [3.5e-323 2.5e-323 9.9e-324 2.5e-323]
 [2.5e-323 2.0e-323 4.0e-323 2.0e-323]
 [2.0e-323 0.0e+000 0.0e+000 2.0e-323]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[45.59039124 56.26635195 50.14008362 52.04278597]
 [52.69642824 42.25076496 53.6473226  48.36522617]
 [55.70668386 52.2621831  38.82515617 56.3523883 ]]
Array a0:
 [[2 6 9 4]
 [3 1 0 8]
 [7 5 2 5]
 [5 4 8 4]
 [4 0 0 4]]
Array sum a0:
 81
